name: Test Org Secret
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - env:
          T: ${{ secrets.RUNNER_STATUS_TOKEN }}
        run: |
          echo "len=${#T}"
